#!/bin/bash

# Quick Commands for CardioSense Backend Testing
# Copy and paste these commands to test the models

echo "CardioSense - Quick Commands"
echo ""
echo "1. Initialize Model Cache"
echo "   python3 code/init_model_cache.py"
echo ""
echo "2. Start API Server"
echo "   cd app && python3 -m uvicorn main:app --reload --host 127.0.0.1 --port 8000"
echo ""
echo "3. Test All Models (in another terminal)"
echo "   python3 test_all_models.py"
echo ""
echo "4. Open Swagger UI"
echo "   http://127.0.0.1:8000/docs"
echo ""
echo "5. Test Individual Model with cURL"
echo ""
echo "   # RandomForest"
echo "   curl -X POST http://127.0.0.1:8000/predict \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"features\": [...278 numbers...], \"model\": \"RandomForest\"}'"
echo ""
echo "   # XGBoost"
echo "   curl -X POST http://127.0.0.1:8000/predict \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"features\": [...278 numbers...], \"model\": \"XGBoost\"}'"
echo ""
echo "   # SVM"
echo "   curl -X POST http://127.0.0.1:8000/predict \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"features\": [...278 numbers...], \"model\": \"SVM\"}'"
echo ""
echo "   # LogisticRegression"
echo "   curl -X POST http://127.0.0.1:8000/predict \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"features\": [...278 numbers...], \"model\": \"LogisticRegression\"}'"
echo ""
echo "6. Get All Models"
echo "   curl http://127.0.0.1:8000/models | python3 -m json.tool"
echo ""
echo "7. Health Check"
echo "   curl http://127.0.0.1:8000/health | python3 -m json.tool"
echo ""
echo "8. Start Frontend"
echo "   cd front-end && npm run dev"
echo ""
echo "Access frontend at: http://localhost:3000"
